using Microsoft.Extensions.Logging;

namespace SunAuto.Logging.Client;

/// <summary>
/// Represents a single log entry that is queued for sending to Splunk via the HTTP Event Collector (HEC). This class encapsulates the details of a log message, including its level, event ID, state, formatted message, exception (if any), and timestamp.
/// </summary>
public class QueueEntry
{
    /// <summary>
    /// The log level of the entry, indicating the severity of the log message (e.g., Information, Warning, Error).
    /// </summary>
    public LogLevel Loglevel { get; set; }

    /// <summary>
    /// The event ID associated with the log entry, which can be used to categorize or identify specific events in the logging system.
    /// </summary>
    public EventId EventId { get; set; }

    /// <summary>
    /// The state object associated with the log entry, which can contain additional contextual information relevant to the log message. This property can be null if no state is provided.
    /// </summary>
    public object? State { get; set; }

    /// <summary>
    /// The formatted log message that will be sent to Splunk. This property is generated by the formatter function provided when logging the message and may include details from the state and exception. It can be null if no formatted message is available.
    /// </summary>
    public string? Formatted { get; set; }

    /// <summary>
    /// The exception associated with the log entry, if any. This property captures any exception that occurred during the operation being logged and can provide valuable debugging information. It can be null if no exception is present.
    /// </summary>
    public Exception? Exception { get; set; }

    /// <summary>
    /// The object ID of the user associated with the log entry, captured when the entry was created.
    /// It can be null if no <see cref="LoggerOptions.UserIdResolver"/> is configured or no user is authenticated.
    /// </summary>
    public Guid? UserId { get; set; }

    /// <summary>
    /// The timestamp indicating when the log entry was created. This property is set to the current UTC time when the QueueEntry instance is created and can be used to track when the log event occurred.
    /// </summary>
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Returns a string representation of the QueueEntry, including its timestamp, log level, event ID, formatted message, and exception details (if any). This method is useful for debugging and logging purposes, providing a human-readable summary of the log entry's contents.
    /// </summary>
    /// <returns></returns>
    public override string ToString()
    {
        var levelLabel = Loglevel.ToString();
        var eventId = EventId.Id != 0 ? $"[{EventId.Id}]" : string.Empty;
        var exceptionMessage = Exception is not null ? $" Exception: {Exception}" : string.Empty;
        return $"{Timestamp:O} {levelLabel} {eventId} {Formatted}{exceptionMessage}";
    }
}