# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'd678bcf5-2503-42bb-b505-dd53a0081d3f/fa996d31-77ec-485a-ab34-ecf8c67ade69'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/DotnetLogging.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd678bcf5-2503-42bb-b505-dd53a0081d3f/fa996d31-77ec-485a-ab34-ecf8c67ade69'
    allowPackageConflicts: true
