trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    projects: '**/DotnetClient.csproj'
    feedsToUse: 'select'
    vstsFeed: '6673237b-3ab0-455c-9685-3a783656608e/87d5524c-c60d-4dd7-8c5a-41127d611388'

- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    projects: '**/DotnetClient.csproj'
    configuration: 'Release'

# - task: DotNetCoreCLI@2
#   name: Test
#   inputs:
#     command: 'test'
#     projects: '**/DotnetClientTest.csproj'
    
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '0a6afb71-e01b-42b3-8b05-aaf61f56fcbb/8db8fe12-9df0-422a-92aa-de9c3fe56e6a'
    allowPackageConflicts: true
