trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    projects: '**/DotnetClient.csproj'
    feedsToUse: 'select'
    vstsFeed: '6074c033-a73a-4acc-b238-58eec6c81c92'

- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    projects: '**/DotnetClient.csproj'
    configuration: 'Release'

# - task: DotNetCoreCLI@2
#   name: Test
#   inputs:
#     command: 'test'
#     projects: '**/DotnetClientTest.csproj'
    
- task: DotNetCoreCLI@2
  name: Push
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd678bcf5-2503-42bb-b505-dd53a0081d3f/fa996d31-77ec-485a-ab34-ecf8c67ade69'
    
    