trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    projects: '**/DotnetClient.csproj'
    feedsToUse: 'select'
    vstsFeed: 'f498e404-b031-4026-8079-fa413a817b22'

- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    projects: '**/DotnetClient.csproj'
    configuration: 'Release'

- task: DotNetCoreCLI@2
  name: Test
  inputs:
    command: 'test'
    projects: '**/DotnetClientTest.csproj'
    
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f498e404-b031-4026-8079-fa413a817b22'
    allowPackageConflicts: true
