# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    projects: '**/DotnetLogging.csproj'
    feedsToUse: 'select'
    vstsFeed: '0a6afb71-e01b-42b3-8b05-aaf61f56fcbb/8db8fe12-9df0-422a-92aa-de9c3fe56e6a'

- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    projects: '**/DotnetLogging.csproj'
    configuration: 'Release'

- task: DotNetCoreCLI@2
  name: Test
  inputs:
    command: 'test'
    projects: '**/Test.csproj'
    
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '0a6afb71-e01b-42b3-8b05-aaf61f56fcbb/8db8fe12-9df0-422a-92aa-de9c3fe56e6a'
    allowPackageConflicts: true
