# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    projects: '**/DotnetLogging.csproj'
    feedsToUse: 'select'
    vstsFeed: '6074c033-a73a-4acc-b238-58eec6c81c92'

- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    projects: '**/DotnetLogging.csproj'
    configuration: 'Release'

- task: DotNetCoreCLI@2
  name: Test
  inputs:
    command: 'test'
    projects: '**/Test.csproj'
    
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    command: push
    feedsToUse: 'select'
    publishVstsFeed: 'feedname'
    allowPackageConflicts: true
