    
trigger:
- dev

pool:
  vmImage: 'windows-latest'
steps:

- task: NuGetCommand@2
  name: "Restore"
  displayName: "Restore NuGet dependencies"
  inputs:
    command: 'restore'
    restoreSolution: '**/*All.sln'
    feedsToUse: 'select'
    vstsFeed: 'f498e404-b031-4026-8079-fa413a817b22'
    noCache: true
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Service.csproj'
    arguments: '--configuration Debug --output publish_output'
    zipAfterPublish: false
    modifyOutputPath: false

- task: VSBuild@1
  name: "Build"
  displayName: "Build assemblies"
  inputs:
    solution: '**/Service.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: 'Any CPU'
    configuration: 'Debug'

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'

- task: AzureFunctionApp@2 # Add this at the end of your file
  inputs:
    connectedServiceNameARM: 'UniversalLoggingServiceConnection'
    appType: 'functionAppLinux'
    appName: 'SunAutoLogging'
    deployToSlotOrASE: true
    resourceGroupName: 'IT-Development-Resource-Group'
    slotName: 'dev'
    package: '$(System.ArtifactsDirectory)/**/*.zip'
    deploymentMethod: 'auto'
