trigger:
- none

pool:
  vmImage: 'windows-latest'
steps:

- task: NuGetCommand@2
  name: "Restore"
  displayName: "Restore NuGet dependencies"
  inputs:
    command: 'restore'
    restoreSolution: '**/*All.sln'
    feedsToUse: 'select'
    vstsFeed: 'f498e404-b031-4026-8079-fa413a817b22'
    noCache: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Service.csproj'
    arguments: '--configuration Release --output publish_output'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'

- task: AzureFunctionApp@2 # Add this at the end of your file
  inputs:
    connectedServiceNameARM: 'UniversalLoggingServiceConnection'
    appType: 'functionAppLinux'
    appName: 'SunAutoLogging'
    package: '$(System.ArtifactsDirectory)/**/*.zip'
    deploymentMethod: 'auto'
